# -*- coding: utf-8 -*-
"""
/***************************************************************************
 CCMonitoringToolbox
                                 A QGIS plugin
 This plugin facilitates the implementation of the Cool Cities monitoring strategy for urban cooling projects.
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2026-05-06
        copyright            : (C) 2026 by Kirya Heinemann, HafenCity University
        email                : kirya.heinemann@hcu-hamburg.de
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""

__author__ = 'Kirya Heinemann, HafenCity University'
__date__ = '2026-05-06'
__copyright__ = '(C) 2026 by Kirya Heinemann, HafenCity University'


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load CCMonitoringToolbox class from file CCMonitoringToolbox.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .cc_monitoring_toolbox import CCMonitoringToolboxPlugin
    return CCMonitoringToolboxPlugin()
