# -*- coding: utf-8 -*-

"""
/***************************************************************************
 CCMonitoringToolbox
                                 A QGIS plugin
 This plugin facilitates the implementation of the Cool Cities monitoring strategy for urban cooling projects.
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2026-05-06
        copyright            : (C) 2026 by Kirya Heinemann, HafenCity University
        email                : kirya.heinemann@hcu-hamburg.de
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

__author__ = 'Kirya Heinemann, HafenCity University'
__date__ = '2026-05-06'
__copyright__ = '(C) 2026 by Kirya Heinemann, HafenCity University'

# This will get replaced with a git SHA1 when you do a git archive

__revision__ = '$Format:%H$'

import os
import sys
import inspect

from qgis.core import QgsProcessingAlgorithm, QgsApplication
from .cc_monitoring_toolbox_provider import CCMonitoringToolboxProvider

cmd_folder = os.path.split(inspect.getfile(inspect.currentframe()))[0]

if cmd_folder not in sys.path:
    sys.path.insert(0, cmd_folder)


class CCMonitoringToolboxPlugin(object):

    def __init__(self):
        self.provider = None

    def initProcessing(self):
        """Init Processing provider for QGIS >= 3.8."""
        self.provider = CCMonitoringToolboxProvider()
        QgsApplication.processingRegistry().addProvider(self.provider)

    def initGui(self):
        self.initProcessing()

    def unload(self):
        QgsApplication.processingRegistry().removeProvider(self.provider)
