# -*- coding: utf-8 -*-

"""
/***************************************************************************
 CCMonitoringToolbox
                                 A QGIS plugin
 This plugin facilitates the implementation of the Cool Cities monitoring strategy for urban cooling projects.
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2026-05-06
        copyright            : (C) 2026 by Kirya Heinemann, HafenCity University
        email                : kirya.heinemann@hcu-hamburg.de
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

__author__ = 'Kirya Heinemann, HafenCity University'
__date__ = '2026-05-06'
__copyright__ = '(C) 2026 by Kirya Heinemann, HafenCity University'

# This will get replaced with a git SHA1 when you do a git archive

__revision__ = '$Format:%H$'

from qgis.PyQt.QtCore import QCoreApplication
from qgis.core import (QgsProcessing,
                       QgsFeatureSink,
                       QgsProcessingAlgorithm,
                       QgsProcessingParameterFeatureSource,
                       QgsProcessingParameterFeatureSink)


class CCMonitoringToolboxAlgorithm(QgsProcessingAlgorithm):
    """
    This is an example algorithm that takes a vector layer and
    creates a new identical one.

    It is meant to be used as an example of how to create your own
    algorithms and explain methods and variables used to do it. An
    algorithm like this will be available in all elements, and there
    is not need for additional work.

    All Processing algorithms should extend the QgsProcessingAlgorithm
    class.
    """

    # Constants used to refer to parameters and outputs. They will be
    # used when calling the algorithm from another algorithm, or when
    # calling from the QGIS console.

    OUTPUT = 'OUTPUT'
    INPUT = 'INPUT'

    def initAlgorithm(self, config=None):
        self.addParameter(
            QgsProcessingParameterFeatureSource(
                'INPUT', 'Tree layer', [QgsProcessing.TypeVectorPolygon]
            )
        )
        self.addParameter(
            QgsProcessingParameterField(
                'HEIGHT_FIELD', 'Field of height (m)', 'INPUT'
            )
        )
        self.addParameter(
            QgsProcessingParameterNumber(
                'AZIMUTH', 'Azimuth angle of the sun (0-360°)', 
                type=QgsProcessingParameterNumber.Double, defaultValue=197.21
            )
        )
        self.addParameter(
            QgsProcessingParameterNumber(
                'ALTITUDE', 'Altitude angle of the sun (0-90°)', 
                type=QgsProcessingParameterNumber.Double, defaultValue=59.06
            )
        )
        self.addParameter(
            QgsProcessingParameterFeatureSink(
                'OUTPUT', 'Shadow layer'
            )
        )

    def initAlgorithm(self, config=None):
        # 1. Input layer (Trees)
        self.addParameter(
            QgsProcessingParameterFeatureSource(
                'INPUT', 'Tree layer', [QgsProcessing.TypeVectorPolygon]
            )
        )
        # 2. Selection of field of heights
        self.addParameter(
            QgsProcessingParameterField(
                'HEIGHT_FIELD', 'Field of height (m)', 'INPUT'
            )
        )
        # 3. Azimuth angle
        self.addParameter(
            QgsProcessingParameterNumber(
                'AZIMUTH', 'Azimuth angle of the sun (0-360°)', 
                type=QgsProcessingParameterNumber.Double, defaultValue=197.21
            )
        )
        # 4. Altitude angle
        self.addParameter(
            QgsProcessingParameterNumber(
                'ALTITUDE', 'Altitude angle of the sun (0-90°)', 
                type=QgsProcessingParameterNumber.Double, defaultValue=59.06
            )
        )
        # 5. Output-Layer
        self.addParameter(
            QgsProcessingParameterFeatureSink(
                'OUTPUT', 'Shadow layer'
            )
        )

    def processAlgorithm(self, parameters, context, feedback):
        import math
        source = self.parameterAsSource(parameters, 'INPUT', context)
        height_field = self.parameterAsField(parameters, 'HEIGHT_FIELD', parameters)
        azimuth = self.parameterAsDouble(parameters, 'AZIMUTH', parameters)
        altitude = self.parameterAsDouble(parameters, 'ALTITUDE', parameters)

        (sink, dest_id) = self.parameterAsSink(
            parameters, 'OUTPUT', context, source.fields(), source.wkbType(), source.sourceCrs()
        )

        # Conversion to radians
        alpha = math.radians(azimuth)
        beta = math.radians(altitude)

        features = source.getFeatures()
        for feature in features:
            if feedback.isCanceled():
                break

            h = feature[height_field]
            if h is None or h <= 0:
                sink.addFeature(feature, QgsFeatureSink.FastInsert)
                continue

            # Shadow calculation
            dist = h / math.tan(beta)
            dx = -1 * dist * math.sin(alpha)
            dy = -1 * dist * math.cos(alpha)

            # Replace geometries
            geom = feature.geometry()
            shadow_geom = geom.translated(dx, dy)
            
            # Connect tree polygon with its moved geometry to obtain one object
            combined_geom = geom.combine(shadow_geom).convexHull()
            
            new_feature = QgsFeature(feature)
            new_feature.setGeometry(combined_geom)
            sink.addFeature(new_feature, QgsFeatureSink.FastInsert)

        return {'OUTPUT': dest_id}

    def name(self):
        """
        Returns the algorithm name, used for identifying the algorithm. This
        string should be fixed for the algorithm, and must not be localised.
        The name should be unique within each provider. Names should contain
        lowercase alphanumeric characters only and no spaces or other
        formatting characters.
        """
        return 'Shadow Generator'

    def displayName(self):
        """
        Returns the translated algorithm name, which should be used for any
        user-visible display of the algorithm name.
        """
        return self.tr(self.name())

    def group(self):
        """
        Returns the name of the group this algorithm belongs to. This string
        should be localised.
        """
        return self.tr(self.groupId())

    def groupId(self):
        """
        Returns the unique ID of the group this algorithm belongs to. This
        string should be fixed for the algorithm, and must not be localised.
        The group id should be unique within each provider. Group id should
        contain lowercase alphanumeric characters only and no spaces or other
        formatting characters.
        """
        return 'Cooling'

    def tr(self, string):
        return QCoreApplication.translate('Processing', string)

    def createInstance(self):
        return CCMonitoringToolboxAlgorithm()
