# -*- coding: utf-8 -*-

"""
/***************************************************************************
 CCMonitoringToolbox
                                 A QGIS plugin
 This plugin facilitates the implementation of the Cool Cities monitoring strategy for urban cooling projects.
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                               -------------------
        begin                : 2026-05-06
        copyright            : (C) 2026 by Kirya Heinemann, HafenCity University
        email                : kirya.heinemann@hcu-hamburg.de
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

__author__ = 'Kirya Heinemann, HafenCity University'
__date__ = '2026-05-06'
__copyright__ = '(C) 2026 by Kirya Heinemann, HafenCity University'

# Cooling
from qgis.core import QgsProcessingProvider
from .cc_monitoring_toolbox_algorithm_C1_PET import CCMonitoringToolboxAlgorithmPET
from .cc_monitoring_toolbox_algorithm_C2_tree_shadow import CCMonitoringToolboxAlgorithmTreeShadow
from .cc_monitoring_toolbox_algorithm_C3_building_shadow import CCMonitoringToolboxAlgorithmBuildingShadow
from .cc_monitoring_toolbox_algorithm_C4_module_shadow import CCMonitoringToolboxAlgorithmModuleShadow
from .cc_monitoring_toolbox_algorithm_C5_shadow_area_use import CCMonitoringToolboxAlgorithmShadowAreaUse
from .cc_monitoring_toolbox_algorithm_C6_Surface_material import CCMonitoringToolboxAlgorithmSurfaceMaterial

# Greening Algorithms
from .cc_monitoring_toolbox_algorithm_G1_Green_quantity import CCMonitoringToolboxAlgorithmGreenQuantity
from .cc_monitoring_toolbox_algorithm_G3_Green_accessibility import CCMonitoringToolboxAlgorithmAccessibility

# Water management
from .cc_monitoring_toolbox_algorithm_W1_infiltration_potential import CCMonitoringToolboxAlgorithmInfiltrationPotential


class CCMonitoringToolboxProvider(QgsProcessingProvider):

    def __init__(self):
        """Default constructor."""
        QgsProcessingProvider.__init__(self)

    def unload(self):
        """Unloads the provider."""
        pass

    def loadAlgorithms(self):
        """Loads all algorithms belonging to this provider."""
        # Register Cooling algorithms
        self.addAlgorithm(CCMonitoringToolboxAlgorithmPET())
        self.addAlgorithm(CCMonitoringToolboxAlgorithmTreeShadow())
        self.addAlgorithm(CCMonitoringToolboxAlgorithmBuildingShadow())
        self.addAlgorithm(CCMonitoringToolboxAlgorithmShadowAreaUse())
        self.addAlgorithm(CCMonitoringToolboxAlgorithmModuleShadow())
        self.addAlgorithm(CCMonitoringToolboxAlgorithmSurfaceMaterial())
        
        
        # Register Greening algorithms
        self.addAlgorithm(CCMonitoringToolboxAlgorithmGreenQuantity())
        self.addAlgorithm(CCMonitoringToolboxAlgorithmAccessibility())
        
        # Register Water management algorithms
        self.addAlgorithm(CCMonitoringToolboxAlgorithmInfiltrationPotential())

    def id(self):
        """Returns the unique provider id."""
        return 'CC_Monitoring_Toolbox'

    def name(self):
        """Returns the provider name."""
        return self.tr('CC Monitoring Toolbox')

    def icon(self):
        """Returns the provider icon."""
        return QgsProcessingProvider.icon(self)

    def longName(self):
        """Returns a longer version of the provider name."""
        return self.name()